myanimechart:
  home-url: ${myanimechart_home_url}

myanimelist:
  client-id: ${myanimechart_myanimelist_client_id}
  client-secret: ${myanimechart_myanimelist_client_secret}
  redirect-uri: ${myanimechart_myanimelist_redirect_uri}
