cors:
  allowed-origins: ${myanimechart_cors_allowed_origins}

myanimelist:
  clientId: ${myanimechart_myanimelist_client_id}

discord:
  webhookUrl: ${myanimechart_discord_webhook_url}

eureka:
  instance:
    hostname: localhost
    non-secure-port-enabled: true
    secure-port-enabled: false
    statusPageUrl: http://${eureka.hostname}:${server.port}/actuator/info
    healthCheckUrl: http://${eureka.hostname}:${server.port}/actuator/health
    homePageUrl: http://${eureka.hostname}:${server.port}/
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${myanimechart_serviceregistry_url}

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  ssl:
    enabled: false

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mariadb://${myanimechart_mariadb_url}
    username: ${myanimechart_mariadb_username}
    password: ${myanimechart_mariadb_password}
  flyway:
    enabled: true
    locations: classpath:flyway
    baseline-on-migrate: true
    validate-on-migrate: true
    fail-on-missing-locations: true

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    p6spy: INFO
