cors:
  allowed-origins: ${myanimechart_cors_allowed_origins}

myanimelist:
  clientId: ${myanimechart_myanimelist_client_id}

discord:
  webhookUrl: ${myanimechart_discord_webhook_url}

eureka:
  instance:
    hostname: api.myanimechart.com
    non-secure-port-enabled: false
    secure-port-enabled: true
    statusPageUrl: https://${eureka.hostname}:${server.port}/actuator/info
    healthCheckUrl: https://${eureka.hostname}:${server.port}/actuator/health
    homePageUrl: https://${eureka.hostname}:${server.port}/
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${myanimechart_serviceregistry_url}

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  ssl:
    key-store: ${myanimechart_keystore_path}
    key-store-password: ${myanimechart_keystore_password}
    key-store-type: JKS
    key-alias: ${myanimechart_keystore_alias}
    trust-store: ${myanimechart_truststore_path}
    trust-store-password: ${myanimechart_truststore_password}
    trust-store-type: JKS

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${myanimechart_mariadb_url}
    username: ${myanimechart_mariadb_username}
    password: ${myanimechart_mariadb_password}
  jpa:
    hibernate:
      show-sql: true
      format-sql: true
  flyway:
    enabled: true
    locations: classpath:flyway-common
    baseline-on-migrate: true
    validate-on-migrate: true
    fail-on-missing-locations: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.stat=: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
